name: E2E Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    if: github.actor != 'eemoji-bot'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
        node-version: [18.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      - name: Install eemoji
        run: pnpm i --ignore-scripts

      - name: Build eemoji
        run: pnpm run build

      - name: Setup eemoji
        run: pnpm run postinstall

      - name: Set git bot
        run: |
          git config --global user.email "eemoji-bot@users.noreply.github.com"
          git config --global user.name "eemoji-bot"

      - name: Make a commit with a keyword
        run: 'git commit --allow-empty -m ''test: eemoji'''

      - name: Check the commit message for emoji
        run: git log -1 --pretty=%B | grep -q "👍"
