name: E2E Test

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        # os: [windows-latest, ubuntu-latest, macos-latest]
        os: [ubuntu-latest]
        node-version: [18.x]
    steps:
      - uses: actions/checkout@v3

      - name: Install pnpm
        uses: pnpm/action-setup@v2

      - name: Set node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: pnpm

      # - name: Install eemoji
      #   run: pnpm i -g eemoji

      - name: Install eemoji
        env:
          SKIP_POSTINSTALL: true
        run: pnpm i

      - name: Build eemoji
        run: pnpm run build

      - name: Setup eemoji
        run: node ./bin/eemoji.mjs init -c none

      - name: Find .git/COMMIT_EDITMSG and print where it is
        run: find . -name COMMIT_EDITMSG

      - name: Find eemoji.mjs and print where it is
        run: find . -name eemoji.mjs
      
      - name: Switch to test branch
        run: git checkout -b test

      - name: Set git bot
        run: |
          git config --global user.email "eemoji-bot@users.noreply.github.com"
          git config --global user.name "eemoji-bot"

      - name: Authenticate with GitHub
        run: 'git config --global http.https://github.com/.extraheader ''AUTHORIZATION: bearer ${{ secrets.BOT_PAT }}'''

      - name: Make a commit with a keyword
        run: 'git commit --allow-empty -m ''test: eemoji'''

      - name: Check the commit message for emoji
        run: |
          git log -1
          git log -1 --pretty=%B | grep -q "👍"
